# <나는 네이버 프런트엔드 개발자입니다 3장>

프론트엔드가 가져야 할 기량들을 설명해준다. 신박하고 중요한 내용이 많아보였다.

- 자격증보단 깃허브
- TIL 리포지토리

# JEST 공부 노트

(Async 관련 내용까지 진행)

[Getting Started · Jest (jestjs.io)](https://jestjs.io/docs/getting-started)

JS 테스팅 기능

99F 프로젝트 폴더에서 발견하여 알게 되었다.

---

되게 간단한데?

```js
const sum = require("./sum")

test('1 + 2 = 3', () => {
    expect(sum(1, 2)).toBe(3);
})

// use `.not` to negate the test
test('3 + 2 != 6', () => {
    expect(sum(3, 2)).not.toBe(3);
})

// use `toEqual` to test 'value equality.'
test('2+5=7, 5+6=11', () => {
    const obj = {
        a: sum(2, 5),
        b: sum(5, 6),
        c: undefined,
        // +) If you also would like to check undefined properties...
    }

    expect(obj).toEqual({
        a: 7,
        b: 11,
    })
    expect(obj).not.toStrictEqual({
        a: 7,
        b: 11,
    }) // Use toStrictEqual instead!
})

// Async Testing
test("I think... 2 + 2 > 3?", () => {
    const promise = new Promise(res => {
        setTimeout(() => {
            res(sum(2, 2))
        }, 1000)
    })

    // DON'T FORGET to RETURN THE PROMISE!
    return promise.then(data => {expect(data).toBeGreaterThan(3)})
})

// Async Testing Again (with await)
test("I think... 5 + 4 < 11?", async () => {
    const promise = new Promise(res => {
        setTimeout(() => {
            res(sum(5, 4))
        }, 1000)
    })

    // DON'T FORGET to RETURN THE PROMISE!
    const data = await promise;
    expect(data).toBeLessThan(11);
})

// Async Catch
test("Too big input", async () => {
    const delay = new Promise(res => {
        setTimeout(res, 1000)
    })

    expect.assertions(1) // assert the count of matchers
    return delay.then(() => {
        const nan = sum(100000000, 4)
    }).catch(error => {
        expect(error.message).toMatch(/too big/i);
    });
})
```

240427: Async 체크 배우던 중

[Testing Asynchronous Code · Jest (jestjs.io)](https://jestjs.io/docs/asynchronous#asyncawait)
(에러 체크 다소 복잡, `expect.assertions(1)` = 1개의 오류 예상)

[[JavaScript] Jest란? (tistory.com)](https://despiteallthat.tistory.com/190#:~:text=Jest%EB%8A%94%20%ED%8E%98%EC%9D%B4%EC%8A%A4%EB%B6%81%EC%97%90%EC%84%9C,%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%EB%A5%BC%20%EB%8C%80%EC%B2%B4%ED%95%98%EA%B3%A0%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4.)

+) setTimeout 내부에 일어난 Error는 처리되지 않음
```js
const promise = new Promise(res => {
	setTimeout(() => {
		res(sum(100000000, 4)) // input too big, will throw error
	}, 1000)
	// 그러나 에러 X
})
```

따라서 아래와 같이 사용하는 것이 바람직 ([node.js - How to handle errors from setTimeout in JavaScript? - Stack Overflow](https://stackoverflow.com/questions/41431605/how-to-handle-errors-from-settimeout-in-javascript))

```js
const delay = new Promise(res => {
	setTimeout(res, 1000)
})

expect.assertions(1) // assert the count of matchers
return delay.then(() => {
	const nan = sum(100000000, 4)
}).catch(error => {
	expect(error.message).toMatch(/too big/i);
});
```
